<a href="https://colab.research.google.com/github/baeck3505/BA_dataFrame/blob/main/ch01_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EA%B8%B0%EB%B3%B8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 학습목표
###1.describe()
###2.파일불러오기
###3.인덱스,컬럼명,데이터 타입 설정
###4.serise
###5.여러개의 조건으로 불린 인덱싱
###6.query()함수로 불린 인덱싱
###7.drop() 및 데이터 삭제 및 내보내기

###이전 영상에서 여러 개의 조건을 가지고 불린 인덱싱을 하는 방법에 대해 알아봤는데요. 이번 레슨에서는 불린 인덱싱을 할 때 유용하게 사용할 수 있는 query() 함수를 소개해 드리려고 합니다.

###일단 예를 들어 '대출 신청자의 수입이 5000 이상이다'를 의미하는 조건식 1개를 가지고 불린 인덱싱을 해 볼게요. 지금까지 배운 방법을 사용하면 아래와 같이 DataFrame 뒤에 대괄호를 쓰고 그 안에 조건식을 넣어 주면 됩니다.

###그런데 DataFrame에 query() 함수를 사용하면 좀 더 간단한 코드로 동일한 결과물을 얻을 수 있어요. 아래와 같이 query() 함수에 따옴표(' 혹은 ") 안에 조건식을 넣어서 값을 넘겨주면 되는데요. 조건식에서 DataFrame에 대한 언급을 생략하고 바로 컬럼 이름만 쓰면 되어서 코드가 좀 더 간결해지는 효과가 있습니다.

loan_df.query('income > 5000')


###이때 조건식에 변수를 사용하는 것도 가능합니다. 예를 들어 income_mean이라는 변수에 대출 신청자들의 수입 평균을 저장해 두었다고 할게요. 그리고 query() 안에 'income > @income_mean' 이런 식으로 써 주면 수입이 평균보다 큰 신청자들의 데이터만 뽑을 수 있습니다. 이때 변수 앞에 @를 쓰지 않으면 오류가 나니까 주의해 주세요!

income_mean = loan_df['income'].mean()

loan_df.query('income > @income_mean')


###그렇다면 조건식 안에 문자열을 넣어야 할 때에는 어떻게 하면 될까요? 예를 들어 지난 레슨에서 만든 조건식처럼 '대출 신청자의 담보 부동산이 도시에 있다'를 의미하는 조건식을 사용하려면, 아래 코드처럼 큰 따옴표(")와 작은 따옴표(')를 함께 활용해야 합니다. 참고로 한 가지 더 알려 드리자면, 컬럼명에 공백이 포함되어 있으면 property area 이런 식으로 컬럼명을 백틱(```)으로 감싸 주면 됩니다. 어렵지 않죠?

loan_df.query("property_area == 'City'")


###그리고 이때 등호나 부등호로 된 식 말고도, True나 False 값을 리턴하는 다양한 형태의 조건식을 사용할 수 있어요. 그 중에서도 in이나 not in 연산자를 많이 활용하는 편인데요. 예를 들어 아래와 같은 코드를 통해 담보 부동산이 City나 Suburb에 해당하는 데이터를 추출할 수 있어요.

loan_df.query("property_area in ['City', 'Suburb']")
loan_df.query("property_area not in ['City', 'Suburb']")


###그리고 query() 함수에서도 마찬가지로 여러 개의 조건을 결합해서 사용할 수 있는데요. 예를 들어 아래와 같이 and(&) 연산자를 사용해서 기혼 상태이고, 수입이 평균보다 많은 신청자들의 데이터를 뽑을 수 있습니다. 물론 not(~)이나 or(|) 연산자도 활용할 수 있고요.

loan_df.query("married == 'Y' & income > @income_mean")


###각각의 조건식을 좀 더 명확하게 볼 수 있도록 괄호로 묶어 줄 수도 있습니다. 특히 not(~) 연산자를 사용하는 경우에는 괄호로 조건식을 묶어 줘야 코드가 예상치 못하게 작동하거나, 오류가 발생하는 걸 방지할 수 있어요.

loan_df.query("(married == 'Y') & (income > @income_mean)")

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
loan_df = pd.read_csv('/content/drive/MyDrive/코드잇csv/loan.csv') #은행대출심사내역
loan_df #맨 위는 컬럼값, 왼쪽은 인덱스

    loan_id married self_employed  income  amount property_area loan_status
0    LP1003       Y             N  4583.0   128.0         Rural           N
1    LP1005       Y             Y  3000.0    66.0          City           Y
2    LP1006       Y             N  2583.0   120.0          City           Y
3    LP1008       N             N  6000.0   141.0          City           Y
4    LP1011       Y             Y  5417.0   267.0          City           Y
..      ...     ...           ...     ...     ...           ...         ...
595  LP2974       Y             N  3232.0   108.0         Rural           Y
596  LP2979       Y             N  4106.0    40.0         Rural           Y
597  LP2983       Y             N  8072.0   253.0          City           Y
598  LP2984       Y             N  7583.0   187.0          City           Y
599  LP2990       N             Y  4583.0   133.0        Suburb           N

[600 rows x 7 columns]

In [ ]:
loan_df.head() #처음5개 로우를 가지고옴

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y

In [ ]:
loan_df.tail() #마지막 5개 로우를 가지고옴

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
595,LP2974,Y,N,3232,108.0,Rural,Y
596,LP2979,Y,N,4106,40.0,Rural,Y
597,LP2983,Y,N,8072,253.0,City,Y
598,LP2984,Y,N,7583,187.0,City,Y
599,LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
loan_df.shape #로우는 600개, 컬럼은 7개(데이터 크기를 알고싶으면?)

(600, 7)

In [ ]:
loan_df.dtypes #컬럼 별 데이터타입을 알고싶으면?

loan_id           object
married           object
self_employed     object
income           float64
amount           float64
property_area     object
loan_status       object
dtype: object

In [ ]:
loan_df.info() #컬럼별로 몇개의 값과 데이터타입을 알수있음
#non-null값은 결측값이 아닌 데이터갯수를 의미
#전체인 600개와 값이 다르면 결측값이 있다는 뜻이며 self값과 loan값에 결측값이 있다는 것을 알 수 있음.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   loan_id           600 non-null    object
 1   married           600 non-null    object
 2   self_employed     568 non-null    object
 3   applicant_income  600 non-null    int64
 4   loan_amount       589 non-null    float64
 5   property_area     600 non-null    object
 6   loan_status       600 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

In [ ]:
loan_df.describe(include='all')
#수치형데이터를 보여줌(결측값을 제외한), all은 모든 데이터를 보여줌

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
count,600,600,568,600.000000,589.000000,600,600
unique,600,2,2,NaN,NaN,3,2
top,LP1003,Y,N,NaN,NaN,Suburb,Y
freq,1,391,488,NaN,NaN,228,408
mean,NaN,NaN,NaN,5412.933333,146.497453,NaN,NaN
std,NaN,NaN,NaN,6160.148245,85.745800,NaN,NaN
min,NaN,NaN,NaN,150.000000,9.000000,NaN,NaN
25%,NaN,NaN,NaN,2880.500000,100.000000,NaN,NaN
50%,NaN,NaN,NaN,3806.000000,128.000000,NaN,NaN
75%,NaN,NaN,NaN,5785.000000,168.000000,NaN,NaN
max,NaN,NaN,NaN,81000.000000,700.000000,NaN,NaN

In [ ]:
loan_df.sort_values(by='loan_amount')
#대출금액을 기준으로 오름차순으로 정렬,결측값은 가장 아래

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
555,LP2840,N,N,2378,9.0,City,N
13,LP1030,Y,N,1299,17.0,City,Y
91,LP1325,N,N,3620,25.0,Suburb,Y
125,LP1482,Y,Y,3459,25.0,Suburb,Y
542,LP2792,Y,N,5468,26.0,Suburb,Y
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [ ]:
loan_df.sort_values(by='loan_amount', ascending=False) #대출양을 내림차순으로 정, 결측값은 가장 아래

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
163,LP1585,Y,N,51763,700.0,City,Y
122,LP1469,N,Y,20166,650.0,City,Y
147,LP1536,Y,N,39999,600.0,Suburb,Y
548,LP2813,Y,Y,19484,600.0,Suburb,Y
359,LP2191,Y,N,19730,570.0,Rural,N
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

#1. loan_df라는 DataFrame에서 각 컬럼의 데이터 타입과 결측치가 아닌 값의 개수를 확인하려면 어떤 코드를 작성해야 하는지 고르세요.
###loan_df.info()


#2. loan_df라는 DataFrame의 통계 정보를 요약해서 보려면 어떤 코드를 작성해야 하는지 고르세요.
###loan_df.describe()

#3. loan_df라는 DataFrame을 applicant_income 컬럼을 기준으로 내림차순 정렬해서 보려면 어떤 코드를 작성해야 하는지 고르세요.
###loan_df.sort_values(by='applicant_income', ascending=False)

#4. loan_df라는 DataFrame의 로우의 개수와 컬럼의 개수를 확인하려면 어떤 코드를 작성해야 하는지 고르세요.
###loan_df.shape

In [ ]:
loan_df = pd.read_excel('/content/drive/MyDrive/코드잇csv/loan.xlsx', sheet_name=1, header=3, usecols='B:H')
loan_df

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.0,Rural,Y
596,LP2979,Y,N,4106,40.0,Rural,Y
597,LP2983,Y,N,8072,253.0,City,Y
598,LP2984,Y,N,7583,187.0,City,Y
599,LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
loan_df = loan_df.set_index('loan_id') #loan_id를 인덱스로 설정
loan_df

,married,self_employed,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.0,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.0,City,Y
LP1008,N,N,6000,141.0,City,Y
LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.0,Rural,Y
LP2979,Y,N,4106,40.0,Rural,Y
LP2983,Y,N,8072,253.0,City,Y
LP2984,Y,N,7583,187.0,City,Y
LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
loan_df.reset_index() #인덱스를 초기화

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.0,Rural,Y
596,LP2979,Y,N,4106,40.0,Rural,Y
597,LP2983,Y,N,8072,253.0,City,Y
598,LP2984,Y,N,7583,187.0,City,Y
599,LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
loan_df

,married,self_employed,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.0,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.0,City,Y
LP1008,N,N,6000,141.0,City,Y
LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.0,Rural,Y
LP2979,Y,N,4106,40.0,Rural,Y
LP2983,Y,N,8072,253.0,City,Y
LP2984,Y,N,7583,187.0,City,Y
LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
loan_df.columns #컬럼들의 이름만 가져올 수 있음

Index(['married', 'self_employed', 'applicant_income', 'loan_amount',
       'property_area', 'loan_status'],
      dtype='object')

In [ ]:
loan_df.columns = ['married', 'self_employed', 'applicant_income', 'loan_amount',
       'property_area', 'loan_status']
       #컬럼이름변경 또는 바꿔야할 컬럼들만 설정할 수 있음

In [ ]:
loan_df

,married,self_employed,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.0,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.0,City,Y
LP1008,N,N,6000,141.0,City,Y
LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.0,Rural,Y
LP2979,Y,N,4106,40.0,Rural,Y
LP2983,Y,N,8072,253.0,City,Y
LP2984,Y,N,7583,187.0,City,Y
LP2990,N,Y,4583,133.0,Suburb,N

In [ ]:
new_columns = {'applicant_income':'income', 'loan_amount':'amount'} #특정컬럼들만 변경해보자

In [ ]:
loan_df.rename(columns=new_columns) #컬럼이름 변경

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.0         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.0          City           Y
LP1008        N             N    6000   141.0          City           Y
LP1011        Y             Y    5417   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.0         Rural           Y
LP2979        Y             N    4106    40.0         Rural           Y
LP2983        Y             N    8072   253.0          City           Y
LP2984        Y             N    7583   187.0          City           Y
LP2990        N             Y    4583   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
loan_df = loan_df.rename(columns=new_columns)
loan_df #변경값을 저장하자

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.0         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.0          City           Y
LP1008        N             N    6000   141.0          City           Y
LP1011        Y             Y    5417   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.0         Rural           Y
LP2979        Y             N    4106    40.0         Rural           Y
LP2983        Y             N    8072   253.0          City           Y
LP2984        Y             N    7583   187.0          City           Y
LP2990        N             Y    4583   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
loan_df.dtypes #데이터타입을 알려면? 또는 바꿀려면?

married           object
self_employed     object
income             int64
amount           float64
property_area     object
loan_status       object
dtype: object

In [ ]:
#인콤컬럼의 인트타입을 실수형으로 바꿔보자
loan_df['income'].astype('float')

loan_id
LP1003    4583.0
LP1005    3000.0
LP1006    2583.0
LP1008    6000.0
LP1011    5417.0
           ...
LP2974    3232.0
LP2979    4106.0
LP2983    8072.0
LP2984    7583.0
LP2990    4583.0
Name: income, Length: 600, dtype: float64

In [ ]:
loan_df['income'] = loan_df['income'].astype('float')
loan_df #바꾼형식을 데이터타입에 대입하자

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y
LP2990        N             Y  4583.0   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
loan_df['amount'] #컬럼 한줄한줄은 시리즈로 이루어져있음, 인덱스 값을 가지고있음

loan_id
LP1003    128.0
LP1005     66.0
LP1006    120.0
LP1008    141.0
LP1011    267.0
          ...
LP2974    108.0
LP2979     40.0
LP2983    253.0
LP2984    187.0
LP2990    133.0
Name: amount, Length: 600, dtype: float64

In [ ]:
loan_df['self_employed'].dtype #오브젝트타입(문자타입)

dtype('O')

In [ ]:
loan_df['self_employed'].describe() #종류는 2개, n이 488개있음

count     568
unique      2
top         N
freq      488
Name: self_employed, dtype: object

In [ ]:
loan_df['self_employed'].unique()
#n,y,결측값 3종류로 이루어져있음,유니크는 시리즈일 때 사용

array(['N', 'Y', nan], dtype=object)

In [ ]:
loan_df['self_employed'].value_counts() #자영업자컬럼의 각각의 수를 알고싶으면?

self_employed
N    488
Y     80
Name: count, dtype: int64

In [ ]:
loan_df['self_employed'].value_counts(dropna=False) #결측값도 포함해서 카운트

self_employed
N      488
Y       80
NaN     32
Name: count, dtype: int64

In [ ]:
loan_df['self_employed'].value_counts(dropna=False, normalize=True) #비율로 알고싶으면?

self_employed
N      0.813333
Y      0.133333
NaN    0.053333
Name: proportion, dtype: float64

In [ ]:
loan_df[['amount','income']] #일부컬럼들만 가져오고싶으면 리스트 활용

         amount  income
loan_id
LP1003    128.0  4583.0
LP1005     66.0  3000.0
LP1006    120.0  2583.0
LP1008    141.0  6000.0
LP1011    267.0  5417.0
...         ...     ...
LP2974    108.0  3232.0
LP2979     40.0  4106.0
LP2983    253.0  8072.0
LP2984    187.0  7583.0
LP2990    133.0  4583.0

[600 rows x 2 columns]

In [ ]:
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y
LP2990        N             Y  4583.0   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
loan_df['property_area'].value_counts(dropna=False, normalize=True) #부동산의 지역별 비중

property_area
Suburb    0.380000
City      0.328333
Rural     0.291667
Name: proportion, dtype: float64

In [ ]:
loan_df #결혼을 했고, 대출금액이 전체평균보다 큰 데이터를 불러오자

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y
LP2990        N             Y  4583.0   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
condition1 = loan_df['married'] == 'Y' #결혼을 했다

In [ ]:
loan_df['income'].mean()

5412.933333333333

In [ ]:
condition2 = loan_df['income'] > loan_df['income'].mean() #대출금액이 평균보다 큰

In [ ]:
laon_df=loan_df[condition1 & condition2]

In [ ]:
loan_df[condition1 | condition2] #결혼을 했거나 전체평균보다 큰 데이터를 불러오자

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2964        Y             N  3987.0   157.0         Rural           Y
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y

[443 rows x 6 columns]

In [ ]:
loan_df[(loan_df['married'] == 'Y') | (loan_df['income'] > loan_df['income'].mean())]
#변수지정 말고 바로 코드를 작성하자

    loan_id married self_employed  income  amount property_area loan_status
0    LP1003       Y             N  4583.0   128.0         Rural           N
1    LP1005       Y             Y  3000.0    66.0          City           Y
2    LP1006       Y             N  2583.0   120.0          City           Y
3    LP1008       N             N  6000.0   141.0          City           Y
4    LP1011       Y             Y  5417.0   267.0          City           Y
..      ...     ...           ...     ...     ...           ...         ...
594  LP2964       Y             N  3987.0   157.0         Rural           Y
595  LP2974       Y             N  3232.0   108.0         Rural           Y
596  LP2979       Y             N  4106.0    40.0         Rural           Y
597  LP2983       Y             N  8072.0   253.0          City           Y
598  LP2984       Y             N  7583.0   187.0          City           Y

[443 rows x 7 columns]

In [ ]:
condition3 = loan_df['property_area'] == 'city'

In [ ]:
loan_df[condition1 | condition2 & ~condition3]
#결혼을 했거나, 수입이 전체 평균보다 크고, 위치가 도시에 있지않은 데이터프레임을 뽑아라

    loan_id married self_employed  income  amount property_area loan_status
0    LP1003       Y             N  4583.0   128.0         Rural           N
1    LP1005       Y             Y  3000.0    66.0          City           Y
2    LP1006       Y             N  2583.0   120.0          City           Y
3    LP1008       N             N  6000.0   141.0          City           Y
4    LP1011       Y             Y  5417.0   267.0          City           Y
..      ...     ...           ...     ...     ...           ...         ...
594  LP2964       Y             N  3987.0   157.0         Rural           Y
595  LP2974       Y             N  3232.0   108.0         Rural           Y
596  LP2979       Y             N  4106.0    40.0         Rural           Y
597  LP2983       Y             N  8072.0   253.0          City           Y
598  LP2984       Y             N  7583.0   187.0          City           Y

[443 rows x 7 columns]

#실습 설명
###대출 신청자들을 여러 개의 그룹으로 나누려고 합니다. 일단 대출이 승낙된 사람들 중에서 자영업자가 아니고, 수입이 중간값 이상인 사람들을 추출하려고 하는데요. 불린 인덱싱을 사용해서 세 가지 조건을 모두 만족하는 데이터를 group1이라는 변수에 저장해 주세요.

###주의 사항: 채점을 위해 가장 마지막 줄에는 group1이라고 입력해서 DataFrame을 출력해 주세요.(이때 print()를 빼고 코드를 작성해 주세요)

In [ ]:
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y
LP2990        N             Y  4583.0   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
condition1 = loan_df['loan_status'] == 'Y'

In [ ]:
condition2 = loan_df['self_employed'] == 'N'

In [ ]:
loan_df['income'].describe()

count      600.000000
mean      5412.933333
std       6160.148245
min        150.000000
25%       2880.500000
50%       3806.000000
75%       5785.000000
max      81000.000000
Name: income, dtype: float64

In [ ]:
condition3 = loan_df['income'] >= loan_df['income'].median()

In [ ]:
group = loan_df[condition1 & condition2 & condition3]
group

        married self_employed   income  amount property_area loan_status
loan_id
LP1008        N             N   6000.0   141.0          City           Y
LP1018        Y             N   4006.0   168.0          City           Y
LP1032        N             N   4950.0   125.0          City           Y
LP1046        Y             N   5955.0   315.0          City           Y
LP1073        Y             N   4226.0   110.0          City           Y
...         ...           ...      ...     ...           ...         ...
LP2959        Y             N  12000.0   496.0        Suburb           Y
LP2964        Y             N   3987.0   157.0         Rural           Y
LP2979        Y             N   4106.0    40.0         Rural           Y
LP2983        Y             N   8072.0   253.0          City           Y
LP2984        Y             N   7583.0   187.0          City           Y

[159 rows x 6 columns]

#실습 설명
###대출 심사 기준이 변경되어 신청자들의 대출 승낙 여부를 다시 심사해야 한다고 합니다. loan_df에서 loan_status 컬럼을 삭제해 주세요.

###주의 사항: 채점을 위해 가장 마지막 줄에는 loan_df라고 입력해서 DataFrame을 출력해 주세요.(이때 print()를 빼고 코드를 작성해 주세요)

In [ ]:
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N  4583.0   128.0         Rural           N
LP1005        Y             Y  3000.0    66.0          City           Y
LP1006        Y             N  2583.0   120.0          City           Y
LP1008        N             N  6000.0   141.0          City           Y
LP1011        Y             Y  5417.0   267.0          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N  3232.0   108.0         Rural           Y
LP2979        Y             N  4106.0    40.0         Rural           Y
LP2983        Y             N  8072.0   253.0          City           Y
LP2984        Y             N  7583.0   187.0          City           Y
LP2990        N             Y  4583.0   133.0        Suburb           N

[600 rows x 6 columns]

In [ ]:
loan_df.drop(columns='loan_status') #컬럼을 삭제하자, 리스트를 사용하면 여러컬럼들을 삭제가능
#인덱스를 삭제할려면? laon_df.drop('LP1006')

        married self_employed  income  amount property_area
loan_id
LP1003        Y             N  4583.0   128.0         Rural
LP1005        Y             Y  3000.0    66.0          City
LP1006        Y             N  2583.0   120.0          City
LP1008        N             N  6000.0   141.0          City
LP1011        Y             Y  5417.0   267.0          City
...         ...           ...     ...     ...           ...
LP2974        Y             N  3232.0   108.0         Rural
LP2979        Y             N  4106.0    40.0         Rural
LP2983        Y             N  8072.0   253.0          City
LP2984        Y             N  7583.0   187.0          City
LP2990        N             Y  4583.0   133.0        Suburb

[600 rows x 5 columns]

##지난 레슨에서는 drop() 함수를 사용해서 컬럼과 로우를 삭제하는 방법에 대해 알아봤습니다. 로우를 삭제할 때는 함수 안에 바로 삭제할 로우의 인덱스 값을 넣어 주면 되고, 컬럼을 삭제할 때는 columns라는 파라미터를 사용해서 삭제할 컬럼의 이름을 넣어 주면 된다고 배웠었죠?

##그런데 drop() 함수를 쓸 때에는 axis라는 파라미터도 많이 사용합니다. axis는 연산을 컬럼 방향으로 할지, 로우 방향으로 할지 정할 수 있는 함수에서 주로 사용되는데요. drop()에서는 이 값에 따라 로우를 삭제할지, 컬럼을 삭제할지 정할 수 있어요.

##일단 drop()에서 axis의 기본값은 로우를 삭제하는 것을 의미하는 0입니다. 즉, 아래와 같이 loan_df에서 인덱스가 LP1006인 로우를 삭제할 때 함수 내부적으로는 loan_df.drop('LP1006', axis=0)처럼 작동하는 거죠.

##참고로 axis='index'라고 써 줘도 똑같이 인덱스 이름을 기준으로 로우를 삭제하게 됩니다. 하지만 어차피 기본값이 로우를 삭제하는 거니까 이런 경우엔 굳이 axis 값을 따로 설정할 필요가 없겠죠?

##그다음으로, 컬럼을 삭제할 땐 axis 값을 1로 설정하면 됩니다. 예를 들어 이전 영상처럼 loan_df에서 married 컬럼을 삭제하려면 아래와 같이 코드를 작성하면 되죠. 그리고 axis=0과 axis='index'가 똑같이 작동하는 것처럼 axis=1과 axis='columns'도 똑같다고 보시면 됩니다.

##즉 컬럼을 삭제할 때는 drop()에서 columns 값에 바로 컬럼명을 넣을 수도 있고, axis 값을 1이나 columns로 줄 수도 있습니다. 두 방법 모두 같은 결과물을 얻을 수 있지만 전자가 코드도 좀 더 짧고, 이해하기 쉽다는 장점이 있어서 영상에서는 columns 파라미터를 사용하는 방식을 설명드렸는데요. 물론 axis를 사용하는 게 더 편하신 분들은 이 방법을 사용하시면 됩니다.

##코드를 작성하는 방식은 사람마다 다르기 때문에 두 가지 방법을 모두 알아 두면 다른 사람이 작성한 코드도 좀 더 쉽게 이해할 수 있겠죠?

##지금까지 DataFrame을 간단히 탐색하고, 원하는 부분만 필터링하고, 수정 및 삭제하는 방법에 대해 알아봤습니다. 이런 과정을 거치면서 기존 DataFrame에 수정 사항이 생기거나, 아니면 아예 새로운 DataFrame을 만들기도 하죠. 이렇게 만들어진 DataFrame을 따로 저장해 두면 훨씬 편합니다. 매번 작업을 할 때마다 원본 파일을 불러와서 처음부터 가공하는 과정을 거칠 필요 없이, 미리 저장해 둔 파일을 불러와서 사용하면 되니까요.

##이번 레슨에서는 데이터를 저장할 때 주로 사용되는 파일 형식인 CSV 파일과 엑셀 파일로 DataFrame을 내보내는 방법에 대해 알아보겠습니다.

##CSV 파일로 내보내기
##먼저 pandas의 to_csv() 함수를 사용하면 DataFrame을 CSV 파일로 내보낼 수 있습니다. 예를 들어 아래와 같이 생긴 loan_df라는 DataFrame을 내보낸다고 할게요.

##loan_df.to_csv('data/loan2.csv', index=False)

In [ ]:
loan_df.to_csv('/content/drive/MyDrive/코드잇csv/loan3.csv', index=False)