<a href="https://colab.research.google.com/github/baeck3505/BA_dataFrame/blob/main/ch05_%EB%82%A0%EC%A7%9C%EC%99%80%EC%8B%9C%EA%B0%84%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#학습목표
##1.데이터타입 설정하기
##2.날짜와 시간데이터 인덱싱하기
##3. 날짜와 시간을 더하고 빼기

In [3]:
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/order.csv')

In [4]:
df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaN,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

#1. 데이터타입 설정하기

In [5]:
df.dtypes
#시간데이터들이 전부 오브젝트타입으로 되어있으니 시간데이터타입으로 변경하자

order_time                      object
category                        object
product_name                    object
price                          float64
quantity                         int64
sales                          float64
days_for_shipping(expected)      int64
shipping_time                   object
dtype: object

In [6]:
#to.date함수를 사용하자
pd.to_datetime(df['order_time'])

0       2015-01-01 04:54:00
1                       NaT
2       2015-01-01 02:27:00
3       2015-01-01 19:58:00
4       2015-01-01 03:51:00
                ...
18045   2018-01-31 10:20:00
18046   2018-01-31 21:53:00
18047   2018-01-31 17:20:00
18048   2018-01-31 12:26:00
18049   2018-01-31 16:59:00
Name: order_time, Length: 18050, dtype: datetime64[ns]

In [9]:
df['order_time'] = pd.to_datetime(df['order_time'])[0]
#데이트타입으로 변경된 값들을 원래 데이터에 저장하자

In [13]:
df['shipping_time'] = pd.to_datetime(df['shipping_time'])
#데이트타입으로 변경된 값들을 원래 데이터에 저장하자

In [14]:
df.dtypes #다시 데이터타입을 바꿔보자

order_time                     datetime64[ns]
category                               object
product_name                           object
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[ns]
dtype: object

In [15]:
#처음부터 데이터타입으로 미리 지정하고 불러오자
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/order.csv', parse_dates=['order_time','shipping_time'])

In [16]:
df.dtypes #잘 변경된 것을 확인

order_time                     datetime64[ns]
category                               object
product_name                           object
price                                 float64
quantity                                int64
sales                                 float64
days_for_shipping(expected)             int64
shipping_time                  datetime64[ns]
dtype: object

In [18]:
df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
1,NaT,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-01-04 09:47:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [19]:
#결측값들을 찾아보자
df.isna().sum()

order_time                     1
category                       0
product_name                   0
price                          0
quantity                       0
sales                          0
days_for_shipping(expected)    0
shipping_time                  0
dtype: int64

In [22]:
#결측값을 지우고 다시 데이터프레임에 저장하자
df = df.dropna()

In [23]:
#날짜값들만 불러오자
df['order_time'].dt.date

0        2015-01-01
2        2015-01-01
3        2015-01-01
4        2015-01-01
5        2015-01-01
            ...
18045    2018-01-31
18046    2018-01-31
18047    2018-01-31
18048    2018-01-31
18049    2018-01-31
Name: order_time, Length: 18049, dtype: object

In [24]:
#년도값들만 불러오자
df['order_time'].dt.year

0        2015
2        2015
3        2015
4        2015
5        2015
         ...
18045    2018
18046    2018
18047    2018
18048    2018
18049    2018
Name: order_time, Length: 18049, dtype: int32

In [25]:
#요일을 불러오자, 0:월요일 ~ 6:일요일
df['order_time'].dt.dayofweek

0        3
2        3
3        3
4        3
5        3
        ..
18045    2
18046    2
18047    2
18048    2
18049    2
Name: order_time, Length: 18049, dtype: int32

#2. 날짜와 시간 데이터 인덱싱하기

In [26]:
df

,order_time,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
0,2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2,2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
3,2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
4,2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
5,2015-01-01 22:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,3,150.00,3,2015-01-03 19:47:00
...,...,...,...,...,...,...,...,...
18045,2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
18046,2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
18047,2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
18048,2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
18049,2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [27]:
#주문시간을 인덱싱 해보자
df.set_index('order_time')

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 19:58:00,Golf Gloves,Clicgear 8.0 Shoe Brush,9.99,2,19.98,6,2015-01-05 12:08:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 22:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,3,150.00,3,2015-01-03 19:47:00
...,...,...,...,...,...,...,...
2018-01-31 10:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,4,2018-02-02 13:53:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00

In [29]:
#주문시간을 기준으로 오름차순을 변경후 저장하자
df = df.set_index('order_time').sort_index()
df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00
...,...,...,...,...,...,...,...
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 18:53:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00

In [30]:
#2015년 데이터만 불러오자, 데이트타입으로 변경하면 유용함
df.loc['2015']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00
...,...,...,...,...,...,...,...
2015-12-31 16:18:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,1,50.00,6,2016-01-04 17:07:00
2015-12-31 18:45:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,5,250.00,4,2016-01-06 11:14:00
2015-12-31 19:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,3,149.94,6,2016-01-03 14:51:00
2015-12-31 20:51:00,Shop By Sport,Under Armour Girls' Toddler Spine Surge Runni,39.99,4,159.96,6,2016-01-02 12:18:00
2015-12-31 22:36:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2016-01-02 13:46:00

In [31]:
#2015년 6월 데이터만 불러오자
df.loc['2015-06']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-06-01 01:00:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-05 19:09:00
2015-06-01 01:42:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,6,2015-06-07 20:58:00
2015-06-01 02:24:00,Shop By Sport,Under Armour Girls' Toddler Spine Surge Runni,39.99,1,39.99,4,2015-06-04 18:16:00
2015-06-01 02:46:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,4,239.96,4,2015-06-05 09:27:00
2015-06-01 02:46:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,4,239.96,4,2015-06-05 14:54:00
...,...,...,...,...,...,...,...
2015-06-30 17:57:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-07-04 19:39:00
2015-06-30 20:04:00,Water Sports,Pelican Sunstream 100 Kayak,199.99,1,199.99,4,2015-07-05 17:14:00
2015-06-30 22:52:00,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,99.99,3,299.97,3,2015-07-02 19:19:00
2015-06-30 23:34:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,3,2015-07-02 18:35:00
2015-06-30 23:34:00,Accessories,Team Golf Tennessee Volunteers Putter Grip,24.99,2,49.98,3,2015-07-02 11:47:00

In [32]:
#2015년부터 2017년까지의 데이터를 슬라이싱 해보자
df.loc['2015':'2017']

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00
...,...,...,...,...,...,...,...
2017-12-31 09:51:00,DVDs,DVDs,164.38,1,164.38,6,2018-01-02 20:35:00
2017-12-31 10:33:00,DVDs,DVDs,164.38,1,164.38,6,2018-01-04 18:24:00
2017-12-31 12:18:00,DVDs,DVDs,164.38,1,164.38,6,2018-01-04 14:33:00
2017-12-31 14:03:00,DVDs,DVDs,164.38,1,164.38,6,2018-01-04 17:07:00
2017-12-31 20:00:00,DVDs,DVDs,164.38,1,164.38,6,2018-01-06 14:40:00

#실습 설명
##익중이는 배달 전문 음식점을 운영하고 있습니다. 다행히 맛집으로 소문이 났는지, 저녁 시간대에 들어오는 주문이 엄청 많아져서 새로운 배달 업체와 계약을 했다고 하네요. 일주일 정도 서비스를 이용해 본 뒤, 배달이 빠르게 잘 되고 있는지 배달 수수료로 얼마를 내고 있는지 등을 전반적으로 확인해 보려고 하는데요.

##일단 이 업체를 이용하기 시작한 날인 2022년 10월 17일의 데이터만 뽑아서 확인해 봅시다. 주문 시각(order_time)을 기준으로 데이터를 추출해 보세요!

In [33]:
delivery_df = pd.read_csv('/content/drive/MyDrive/코드잇csv/delivery.csv')
delivery_df

              order_time  distance  time_taken  num_of_deliveries  charge
0    2022-10-17 18:34:00       3.9          21                  1    4.68
1    2022-10-17 18:35:00       5.2          24                  1    7.02
2    2022-10-17 18:36:00       8.4          36                  2    9.53
3    2022-10-17 18:37:00       3.6          17                  1    6.21
4    2022-10-17 18:41:00       2.6          15                  1    2.44
..                   ...       ...         ...                ...     ...
104  2022-10-23 19:28:00       6.4          37                  1    5.01
105  2022-10-23 19:28:00       3.9          26                  2    7.34
106  2022-10-23 19:48:00       3.3          21                  1    3.83
107  2022-10-23 19:49:00       5.8          22                  1    5.80
108  2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 5 columns]

In [34]:
delivery_df.dtypes #먼저 주문시간을 데이터타입으로 변경하자

order_time            object
distance             float64
time_taken             int64
num_of_deliveries      int64
charge               float64
dtype: object

In [41]:
delivery_df['order_time'] = pd.to_datetime(delivery_df['order_time']) #변경된 값을 저장

In [42]:
delivery_df.dtypes #잘 변경된 것을 확인

order_time           datetime64[ns]
distance                    float64
time_taken                    int64
num_of_deliveries             int64
charge                      float64
dtype: object

In [43]:
df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00
...,...,...,...,...,...,...,...
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 18:53:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00

In [47]:
delivery_df = delivery_df.sort_index() #인덱스를 주문시간으로 변경

In [48]:
delivery_df

                     distance  time_taken  num_of_deliveries  charge
order_time
2022-10-17 18:34:00       3.9          21                  1    4.68
2022-10-17 18:35:00       5.2          24                  1    7.02
2022-10-17 18:36:00       8.4          36                  2    9.53
2022-10-17 18:37:00       3.6          17                  1    6.21
2022-10-17 18:41:00       2.6          15                  1    2.44
...                       ...         ...                ...     ...
2022-10-23 19:28:00       6.4          37                  1    5.01
2022-10-23 19:28:00       3.9          26                  2    7.34
2022-10-23 19:48:00       3.3          21                  1    3.83
2022-10-23 19:49:00       5.8          22                  1    5.80
2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 4 columns]

In [49]:
delivery_df.loc['2022-10-17'] #정답

                     distance  time_taken  num_of_deliveries  charge
order_time
2022-10-17 18:34:00       3.9          21                  1    4.68
2022-10-17 18:35:00       5.2          24                  1    7.02
2022-10-17 18:36:00       8.4          36                  2    9.53
2022-10-17 18:37:00       3.6          17                  1    6.21
2022-10-17 18:41:00       2.6          15                  1    2.44
2022-10-17 18:54:00      15.2          34                  1   13.72
2022-10-17 18:54:00       2.4          14                  1    2.00
2022-10-17 18:54:00      13.7          50                  2    8.74
2022-10-17 18:55:00       7.6          28                  1    5.52
2022-10-17 18:55:00       3.3          16                  1    6.95
2022-10-17 19:16:00       4.7          19                  1    3.54
2022-10-17 19:17:00      12.5          43                  2   14.34
2022-10-17 19:17:00       3.0          16                  1    3.42
2022-10-17 19:19:00       8.5          30                  1   10.30
2022-10-17 19:20:00       5.2          22                  1    3.09
2022-10-17 19:21:00       2.1          14                  1    3.00
2022-10-17 19:21:00      16.5          52                  2   13.78
2022-10-17 19:22:00       8.3          30                  2   13.86

#3. 날짜와 시간을 더하고 빼기

In [50]:
#이번에는 주문시간과 배송시간을 통해 실제로 몇일 걸렸는지 계산해보자
df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time
order_time,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00
...,...,...,...,...,...,...,...
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 18:53:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00

In [51]:
#오른쪽값은 배송소요 시간
df['shipping_time'] - df.index

order_time
2015-01-01 02:27:00   4 days 10:48:00
2015-01-01 03:51:00   3 days 16:15:00
2015-01-01 04:33:00   5 days 13:28:00
2015-01-01 04:54:00   6 days 14:13:00
2015-01-01 07:42:00   4 days 09:23:00
                            ...
2018-01-31 12:26:00   3 days 06:32:00
2018-01-31 16:59:00   6 days 03:33:00
2018-01-31 17:20:00   1 days 16:56:00
2018-01-31 18:44:00   6 days 00:09:00
2018-01-31 21:53:00   1 days 20:57:00
Length: 18049, dtype: timedelta64[ns]

In [52]:
#위 값을 새로운컬럼에 저장하자
df['days_for_shipping(actual)'] = df['shipping_time'] - df.index

In [53]:
#잘 저장됬는지 확인해보자
df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual)
order_time,,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6,2015-01-05 13:15:00,4 days 10:48:00
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6,2015-01-04 20:06:00,3 days 16:15:00
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6,2015-01-06 18:01:00,5 days 13:28:00
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6,2015-01-07 19:07:00,6 days 14:13:00
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4,2015-01-05 17:05:00,4 days 09:23:00
...,...,...,...,...,...,...,...,...
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-03 18:58:00,3 days 06:32:00
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 20:32:00,6 days 03:33:00
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-02 10:16:00,1 days 16:56:00
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6,2018-02-06 18:53:00,6 days 00:09:00
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3,2018-02-02 18:50:00,1 days 20:57:00

In [54]:
df.dtypes #예상시간과 실제시간의 타입이 다르면 오류가 날 수 있으니 같은타입으로 변경하자

category                                object
product_name                            object
price                                  float64
quantity                                 int64
sales                                  float64
days_for_shipping(expected)              int64
shipping_time                   datetime64[ns]
days_for_shipping(actual)      timedelta64[ns]
dtype: object

In [55]:
#일을 기준으로 타임델타를 변경하자
pd.to_timedelta(df['days_for_shipping(expected)'],unit='D')

order_time
2015-01-01 02:27:00   6 days
2015-01-01 03:51:00   6 days
2015-01-01 04:33:00   6 days
2015-01-01 04:54:00   6 days
2015-01-01 07:42:00   4 days
                       ...
2018-01-31 12:26:00   6 days
2018-01-31 16:59:00   6 days
2018-01-31 17:20:00   6 days
2018-01-31 18:44:00   6 days
2018-01-31 21:53:00   3 days
Name: days_for_shipping(expected), Length: 18049, dtype: timedelta64[ns]

In [57]:
#해당값을 저장하고 확인해보자
df['days_for_shipping(expected)'] = pd.to_timedelta(df['days_for_shipping(expected)'],unit='D')

In [58]:
df.dtypes #인트였던 타입이 타임델타로 잘 변경된것을 확인

category                                object
product_name                            object
price                                  float64
quantity                                 int64
sales                                  float64
days_for_shipping(expected)    timedelta64[ns]
shipping_time                   datetime64[ns]
days_for_shipping(actual)      timedelta64[ns]
dtype: object

In [62]:
#이제 예상배송시간보다 오래걸린 데이터들을 불러오자
df['days_for_shipping(expected)'] < df['days_for_shipping(actual)']

order_time
2015-01-01 02:27:00    False
2015-01-01 03:51:00    False
2015-01-01 04:33:00    False
2015-01-01 04:54:00     True
2015-01-01 07:42:00     True
                       ...
2018-01-31 12:26:00    False
2018-01-31 16:59:00     True
2018-01-31 17:20:00    False
2018-01-31 18:44:00     True
2018-01-31 21:53:00    False
Length: 18049, dtype: bool

In [63]:
#해당값들을 새로운 컬럼에 저장하자
df['late_shipping'] = df['days_for_shipping(expected)'] < df['days_for_shipping(actual)']
df

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
order_time,,,,,,,,,
2015-01-01 02:27:00,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,49.98,4,199.92,6 days,2015-01-05 13:15:00,4 days 10:48:00,False
2015-01-01 03:51:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,6 days,2015-01-04 20:06:00,3 days 16:15:00,False
2015-01-01 04:33:00,Fishing,Field & Stream Sportsman 16 Gun Fire Safe,399.98,1,399.98,6 days,2015-01-06 18:01:00,5 days 13:28:00,False
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4 days,2015-01-05 17:05:00,4 days 09:23:00,True
...,...,...,...,...,...,...,...,...,...
2018-01-31 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-03 18:58:00,3 days 06:32:00,False
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 20:32:00,6 days 03:33:00,True
2018-01-31 17:20:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-02 10:16:00,1 days 16:56:00,False
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 18:53:00,6 days 00:09:00,True
2018-01-31 21:53:00,Women's Clothing,Summer dresses,215.82,1,215.82,3 days,2018-02-02 18:50:00,1 days 20:57:00,False

In [65]:
#예상보다 늦게 배송된 건들이 몇개인지 확인해보자 : 3204개
df['late_shipping'].value_counts()

late_shipping
False    14845
True      3204
Name: count, dtype: int64

In [67]:
df[df['late_shipping']] #늦은건수들만 불러오자

,category,product_name,price,quantity,sales,days_for_shipping(expected),shipping_time,days_for_shipping(actual),late_shipping
order_time,,,,,,,,,
2015-01-01 04:54:00,Cleats,Perfect Fitness Perfect Rip Deck,59.99,3,179.97,6 days,2015-01-07 19:07:00,6 days 14:13:00,True
2015-01-01 07:42:00,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.98,1,299.98,4 days,2015-01-05 17:05:00,4 days 09:23:00,True
2015-01-01 08:03:00,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.99,1,129.99,4 days,2015-01-06 12:32:00,5 days 04:29:00,True
2015-01-01 12:57:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-05 15:14:00,4 days 02:17:00,True
2015-01-02 05:04:00,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,50.00,4,200.00,4 days,2015-01-07 12:48:00,5 days 07:44:00,True
...,...,...,...,...,...,...,...,...,...
2018-01-28 20:40:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-03 09:15:00,5 days 12:35:00,True
2018-01-29 12:26:00,Women's Clothing,Summer dresses,215.82,1,215.82,4 days,2018-02-04 16:17:00,6 days 03:51:00,True
2018-01-29 14:11:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-04 20:04:00,6 days 05:53:00,True
2018-01-31 16:59:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 20:32:00,6 days 03:33:00,True
2018-01-31 18:44:00,Women's Clothing,Summer dresses,215.82,1,215.82,6 days,2018-02-06 18:53:00,6 days 00:09:00,True

#실습 설명
##이번에는 배달 음식이 고객에게 도착한 시각을 계산해 봅시다. 주문 시각(order_time)과 배달 소요 시간(time_taken)을 가지고 배달 완료 시간을 계산해서 DataFrame에 delivery_time이라는 컬럼을 추가해 주세요!
#참고로 time_taken 컬럼은 배달에 몇 분이 소요되었는지를 의미하므로, 아래 출력 결과처럼 분을 기준으로 한 Timedelta로 바꿔 주세요. 참고로 분을 의미하는 코드는 T 입니다.

In [68]:
delivery_df

                     distance  time_taken  num_of_deliveries  charge
order_time
2022-10-17 18:34:00       3.9          21                  1    4.68
2022-10-17 18:35:00       5.2          24                  1    7.02
2022-10-17 18:36:00       8.4          36                  2    9.53
2022-10-17 18:37:00       3.6          17                  1    6.21
2022-10-17 18:41:00       2.6          15                  1    2.44
...                       ...         ...                ...     ...
2022-10-23 19:28:00       6.4          37                  1    5.01
2022-10-23 19:28:00       3.9          26                  2    7.34
2022-10-23 19:48:00       3.3          21                  1    3.83
2022-10-23 19:49:00       5.8          22                  1    5.80
2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 4 columns]

In [69]:
#타입을 먼저 알아보자
delivery_df.dtypes

distance             float64
time_taken             int64
num_of_deliveries      int64
charge               float64
dtype: object

In [71]:
#taken타입을 타임델타로 변경하자
delivery_df['time_taken'] = pd.to_timedelta(delivery_df['time_taken'],unit='T')

<ipython-input-71-fbae75b4ab18>:2: FutureWarning: 'T' is deprecated and will be removed in a future version. Please use 'min' instead of 'T'.
  delivery_df['time_taken'] = pd.to_timedelta(delivery_df['time_taken'],unit='T')

In [73]:
#도착한 시간을 계산하는 방법은? 그리고 새로운 컬럼에 저장하자(주문시간과 소요시간을 더하자)
delivery_df['delivery_time'] = delivery_df.index + delivery_df['time_taken']

In [74]:
delivery_df

,distance,time_taken,num_of_deliveries,charge,delivery_time
order_time,,,,,
2022-10-17 18:34:00,3.9,0 days 00:21:00,1,4.68,2022-10-17 18:55:00
2022-10-17 18:35:00,5.2,0 days 00:24:00,1,7.02,2022-10-17 18:59:00
2022-10-17 18:36:00,8.4,0 days 00:36:00,2,9.53,2022-10-17 19:12:00
2022-10-17 18:37:00,3.6,0 days 00:17:00,1,6.21,2022-10-17 18:54:00
2022-10-17 18:41:00,2.6,0 days 00:15:00,1,2.44,2022-10-17 18:56:00
...,...,...,...,...,...
2022-10-23 19:28:00,6.4,0 days 00:37:00,1,5.01,2022-10-23 20:05:00
2022-10-23 19:28:00,3.9,0 days 00:26:00,2,7.34,2022-10-23 19:54:00
2022-10-23 19:48:00,3.3,0 days 00:21:00,1,3.83,2022-10-23 20:09:00
2022-10-23 19:49:00,5.8,0 days 00:22:00,1,5.80,2022-10-23 20:11:00
2022-10-23 19:50:00,4.4,0 days 00:19:00,1,7.78,2022-10-23 20:09:00