<a href="https://colab.research.google.com/github/baeck3505/BA_dataFrame/blob/main/ch06_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%95%A9%EC%B9%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 학습목표
##1. concat()
##2. 조인연산
##3. 컬럼기준 데이터 합치기
##4. merge()
##5. 인덱시 기준 데이터 합치기
##6. join()
##7. 조인한 데이터로 새로운 인사이트 얻기

#1. concat()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##인덱스가 순서대로 설정
##1. pd.concat([df1, df2]), ignore_index=True


##옆으로 합치는 방법
##2. pd.concat([df1, df2]), axis=1)

In [ ]:
import pandas as pd

english_df = pd.DataFrame({
    'name' : ['dongwook', 'sineui', 'ikjoong', 'yoonsoo'],
    'english_score' : [50, 89, 68, 88]
})

english_df2 = pd.DataFrame({
    'name' : ['yoonsoo', 'sowon', 'seungheon', 'liam'],
    'english_score' : [50, 89, 68, 88]
})

In [ ]:
pd.concat([english_df, english_df2])

        name  english_score
0   dongwook             50
1     sineui             89
2    ikjoong             68
3    yoonsoo             88
0    yoonsoo             50
1      sowon             89
2  seungheon             68
3       liam             88

In [ ]:
#인덱스가 순서대로 설정해보자
english_df = pd.concat([english_df, english_df2], ignore_index=True)

In [ ]:
#학생들의 수학점수의 데이터프레임
math_df = pd.DataFrame({
    'name' : ['dongwook', 'sineui', 'ikjoong', 'yoonsoo','yoonsoo', 'sowon','seungheon','liam'],
    'math_score' : [50, 89, 68, 88, 100, 100, 79,90]
})

In [ ]:
math_df

        name  math_score
0   dongwook          50
1     sineui          89
2    ikjoong          68
3    yoonsoo          88
4    yoonsoo         100
5      sowon         100
6  seungheon          79
7       liam          90

In [ ]:
#학생들의 영어점수와 수학점수를 합쳐보자,concat함수는 기본적으로 아래에 데이터를 합침
pd.concat([english_df, math_df])

         name  english_score  math_score
0    dongwook           50.0         NaN
1      sineui           89.0         NaN
2     ikjoong           68.0         NaN
3     yoonsoo           88.0         NaN
4     yoonsoo           50.0         NaN
5       sowon           89.0         NaN
6   seungheon           68.0         NaN
7        liam           88.0         NaN
8     yoonsoo           50.0         NaN
9       sowon           89.0         NaN
10  seungheon           68.0         NaN
11       liam           88.0         NaN
0    dongwook            NaN        50.0
1      sineui            NaN        89.0
2     ikjoong            NaN        68.0
3     yoonsoo            NaN        88.0
4     yoonsoo            NaN       100.0
5       sowon            NaN       100.0
6   seungheon            NaN        79.0
7        liam            NaN        90.0

In [ ]:
#가로로 붙여보자
pd.concat([english_df, math_df],axis=1)

         name  english_score       name  math_score
0    dongwook             50   dongwook        50.0
1      sineui             89     sineui        89.0
2     ikjoong             68    ikjoong        68.0
3     yoonsoo             88    yoonsoo        88.0
4     yoonsoo             50    yoonsoo       100.0
5       sowon             89      sowon       100.0
6   seungheon             68  seungheon        79.0
7        liam             88       liam        90.0
8     yoonsoo             50        NaN         NaN
9       sowon             89        NaN         NaN
10  seungheon             68        NaN         NaN
11       liam             88        NaN         NaN

#실습 설명
##2020년부터 2022년까지 3년 간의 월별 매출액 데이터를 한 번에 모아서 보려고 합니다. 각 연도의 데이터는 sales_2020, sales_2021, sales_2022라는 변수에 각각 저장되어 있는데요. 세 개의 DataFrame을 하나로 합쳐서 sales_df라는 변수에 저장해 주시면 됩니다.

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/코드잇csv/sales_2020.csv')

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/코드잇csv/sales_2021.csv')

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/코드잇csv/sales_2022.csv')

In [ ]:
df1

,year,month,total_orders,gross_sales,discounts,returns,total_sales
0,2020,January,73,8861.50,-129.40,-448.45,8283.65
1,2020,February,56,6908.50,-104.70,-416.20,6387.60
2,2020,March,60,5778.50,-172.20,-1017.20,4589.10
3,2020,April,70,8814.00,-281.40,0.00,8532.60
4,2020,May,54,6677.00,-185.75,-253.80,6237.45
5,2020,June,68,9621.50,-234.45,-17.50,9369.55
6,2020,July,66,6480.00,-51.50,-469.20,5959.30
7,2020,August,55,8025.00,-258.90,-26.00,7740.10
8,2020,September,68,7075.00,-61.70,-281.00,6732.30
9,2020,October,59,5720.00,-88.00,-305.00,5327.00
10,2020,November,91,13025.00,-131.30,-323.85,12569.85
11,2020,December,116,10356.05,-149.85,-414.20,9792.00

In [ ]:
df2

,year,month,total_orders,gross_sales,discounts,returns,total_sales
0,2021,January,83,8923.00,-217.10,-26.25,8679.65
1,2021,February,69,6529.20,-161.35,-118.15,6249.70
2,2021,March,64,7442.70,-226.82,-8.80,7207.08
3,2021,April,81,9406.35,-232.28,-40.00,9134.07
4,2021,May,82,7493.90,-221.25,-1448.02,5824.63
5,2021,June,124,13260.80,-335.40,-1506.53,11418.87
6,2021,July,102,9274.95,-237.87,-689.98,8347.10
7,2021,August,82,7698.70,-140.57,-197.35,7360.78
8,2021,September,79,10582.85,-276.15,0.00,10306.70
9,2021,October,71,7014.50,-277.95,-294.75,6441.80
10,2021,November,140,12002.70,-414.45,-154.40,11433.85
11,2021,December,164,13683.50,-371.20,-928.35,12383.95

In [ ]:
df3

,year,month,total_orders,gross_sales,discounts,returns,total_sales
0,2022,January,87,7811.75,-261.97,-1250.35,6299.43
1,2022,February,63,6523.70,-288.70,-38.70,6196.30
2,2022,March,99,13075.50,-439.85,-981.00,11654.65
3,2022,April,92,6977.00,-285.40,-10.00,6681.60
4,2022,May,96,10082.25,-460.90,-173.35,9448.00
5,2022,June,85,7321.75,-186.02,-165.40,6970.33
6,2022,July,94,9739.20,-447.07,-908.75,8383.38
7,2022,August,105,8839.50,-201.67,-84.37,8553.46
8,2022,September,88,9077.45,-354.89,-853.35,7869.21
9,2022,October,97,9132.25,-279.42,-1572.55,7280.28
10,2022,November,272,23997.90,-776.84,-364.51,22856.55
11,2022,December,342,31183.90,-2269.51,-1311.18,27603.21

In [ ]:
pd.concat([df1, df2, df3])

,year,month,total_orders,gross_sales,discounts,returns,total_sales
0,2020,January,73,8861.50,-129.40,-448.45,8283.65
1,2020,February,56,6908.50,-104.70,-416.20,6387.60
2,2020,March,60,5778.50,-172.20,-1017.20,4589.10
3,2020,April,70,8814.00,-281.40,0.00,8532.60
4,2020,May,54,6677.00,-185.75,-253.80,6237.45
5,2020,June,68,9621.50,-234.45,-17.50,9369.55
6,2020,July,66,6480.00,-51.50,-469.20,5959.30
7,2020,August,55,8025.00,-258.90,-26.00,7740.10
8,2020,September,68,7075.00,-61.70,-281.00,6732.30
9,2020,October,59,5720.00,-88.00,-305.00,5327.00
10,2020,November,91,13025.00,-131.30,-323.85,12569.85
11,2020,December,116,10356.05,-149.85,-414.20,9792.00
0,2021,January,83,8923.00,-217.10,-26.25,8679.65
1,2021,February,69,6529.20,-161.35,-118.15,6249.70
2,2021,March,64,7442.70,-226.82,-8.80,7207.08
3,2021,April,81,9406.35,-232.28,-40.00,9134.07
4,2021,May,82,7493.90,-221.25,-1448.02,5824.63
5,2021,June,124,13260.80,-335.40,-1506.53,11418.87
6,2021,July,102,9274.95,-237.87,-689.98,8347.10
7,2021,August,82,7698.70,-140.57,-197.35,7360.78
8,2021,September,79,10582.85,-276.15,0.00,10306.70
9,2021,October,71,7014.50,-277.95,-294.75,6441.80
10,2021,November,140,12002.70,-414.45,-154.40,11433.85
11,2021,December,164,13683.50,-371.20,-928.35,12383.95
0,2022,January,87,7811.75,-261.97,-1250.35,6299.43
1,2022,February,63,6523.70,-288.70,-38.70,6196.30
2,2022,March,99,13075.50,-439.85,-981.00,11654.65
3,2022,April,92,6977.00,-285.40,-10.00,6681.60
4,2022,May,96,10082.25,-460.90,-173.35,9448.00
5,2022,June,85,7321.75,-186.02,-165.40,6970.33
6,2022,July,94,9739.20,-447.07,-908.75,8383.38
7,2022,August,105,8839.50,-201.67,-84.37,8553.46
8,2022,September,88,9077.45,-354.89,-853.35,7869.21
9,2022,October,97,9132.25,-279.42,-1572.55,7280.28
10,2022,November,272,23997.90,-776.84,-364.51,22856.55
11,2022,December,342,31183.90,-2269.51,-1311.18,27603.21

#join()연산

##1.inner join : 두 데이터의 공통된데이터들만 합쳐줌

##2.left outer join : 왼쪽데이터를 기준으로 데이터를 합치고, 공통이 아닌 데이터들은 결측값으로 표시

##3.Right outer join : 오른쪽데이터를 기준으로 합치고, 고통이 아닌 데이터들은 결측값으로 표시

##4.Full outer join : 모든 데이터들을 합치고 제외된 데이터들은 결측값의 표시

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/employee.csv')

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/코드잇csv/survey.csv')

In [ ]:
df

        id department  location             role resign
0   101929         HR     China            Staff      Y
1   101625    Finance        US  Senior Director      N
2   100298         HR     China          Manager      N
3   101870    Finance  Colombia          Manager      N
4   101318         IT     Japan     Senior Staff      N
..     ...        ...       ...              ...    ...
95  100476         HR  Colombia   Senior Manager      Y
96  100226         HR        UK   Senior Manager      N
97  101331         IT     Korea          Manager      N
98  100036         HR        UK          Manager      N
99  100233      Sales     Japan            Staff      N

[100 rows x 5 columns]

In [ ]:
df2

        id department  career  teamwork  reward  environment
0   101355         HR       5         4       5            4
1   100077      Sales       2         2       4            3
2   101844    Finance       2         3       1            5
3   101929         HR       2         3       2            3
4   101888         HR       4         4       3            3
..     ...        ...     ...       ...     ...          ...
71  101449         HR       4         3       3            5
72  101423    Finance       1         2       1            4
73  101098         IT       1         3       4            4
74  100618         IT       5         2       1            2
75  100488    Finance       5         4       1            5

[76 rows x 6 columns]

In [ ]:
#merge함수 활용하자, 기본적으로 인어조인을 활용!
#어떤 값들을 키값으로  설정할까? 중복될 가능성이 없는 사원번호를 키값으로 하는것이 좋다
#설문조사를 한 대상들만 불러옴
pd.merge(df, df2, on='id')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2,3,2,3
1,101625,Finance,US,Senior Director,N,Finance,2,2,3,1
2,101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
3,100936,HR,Japan,Manager,Y,HR,3,2,2,4
4,100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...,...
71,102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
72,100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
73,100226,HR,UK,Senior Manager,N,HR,2,2,3,4
74,101331,IT,Korea,Manager,N,IT,3,5,4,4
75,100233,Sales,Japan,Staff,N,Sales,4,2,2,5

In [ ]:
#설문조사를 시행하지않는 대상들도 포함(전체직원 정보)
pd.merge(df, df2, on='id', how='left')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
1,101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
2,100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
3,101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
4,101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...
95,100476,HR,Colombia,Senior Manager,Y,HR,1.0,2.0,3.0,5.0
96,100226,HR,UK,Senior Manager,N,HR,2.0,2.0,3.0,4.0
97,101331,IT,Korea,Manager,N,IT,3.0,5.0,4.0,4.0
98,100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
99,100233,Sales,Japan,Staff,N,Sales,4.0,2.0,2.0,5.0

In [ ]:
pd.merge(df, df2, on='id', how='right')

,id,department_x,location,role,resign,department_y,career,teamwork,reward,environment
0,101355,HR,US,Director,N,HR,5,4,5,4
1,100077,Sales,Australia,Staff,Y,Sales,2,2,4,3
2,101844,Finance,UK,Senior Manager,N,Finance,2,3,1,5
3,101929,HR,China,Staff,Y,HR,2,3,2,3
4,101888,HR,Australia,Senior Staff,N,HR,4,4,3,3
...,...,...,...,...,...,...,...,...,...,...
71,101449,HR,Korea,Manager,N,HR,4,3,3,5
72,101423,Finance,US,Manager,Y,Finance,1,2,1,4
73,101098,IT,France,Senior Staff,Y,IT,1,3,4,4
74,100618,IT,Turkey,Senior Staff,N,IT,5,2,1,2
75,100488,Finance,Japan,Senior Staff,Y,Finance,5,4,1,5

In [ ]:
#같은컬럼들의 이름을 바꾸자, 뒤에 _x, y 값들을 변경하자
pd.merge(df, df2, on='id', how='left', suffixes=['', '_x'])

,id,department,location,role,resign,department_x,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
1,101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
2,100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
3,101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
4,101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...
95,100476,HR,Colombia,Senior Manager,Y,HR,1.0,2.0,3.0,5.0
96,100226,HR,UK,Senior Manager,N,HR,2.0,2.0,3.0,4.0
97,101331,IT,Korea,Manager,N,IT,3.0,5.0,4.0,4.0
98,100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
99,100233,Sales,Japan,Staff,N,Sales,4.0,2.0,2.0,5.0

In [ ]:
#다른상황에서는?
df2 = df2.rename(columns={'id':'employee_id'})
df2

    employee_id department  career  teamwork  reward  environment
0        101355         HR       5         4       5            4
1        100077      Sales       2         2       4            3
2        101844    Finance       2         3       1            5
3        101929         HR       2         3       2            3
4        101888         HR       4         4       3            3
..          ...        ...     ...       ...     ...          ...
71       101449         HR       4         3       3            5
72       101423    Finance       1         2       1            4
73       101098         IT       1         3       4            4
74       100618         IT       5         2       1            2
75       100488    Finance       5         4       1            5

[76 rows x 6 columns]

In [ ]:
#키값의 컬럼들의 이름이 다르면?
pd.merge(df, df2, left_on='id', right_on='employee_id')

,id,department_x,location,role,resign,employee_id,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,101929,HR,2,3,2,3
1,101625,Finance,US,Senior Director,N,101625,Finance,2,2,3,1
2,101318,IT,Japan,Senior Staff,N,101318,IT,2,3,5,5
3,100936,HR,Japan,Manager,Y,100936,HR,3,2,2,4
4,100125,HR,Korea,Senior Staff,N,100125,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...
71,102031,IT,Colombia,Senior Manager,Y,102031,IT,1,3,3,1
72,100476,HR,Colombia,Senior Manager,Y,100476,HR,1,2,3,5
73,100226,HR,UK,Senior Manager,N,100226,HR,2,2,3,4
74,101331,IT,Korea,Manager,N,101331,IT,3,5,4,4
75,100233,Sales,Japan,Staff,N,100233,Sales,4,2,2,5

In [ ]:
company_df = pd.merge(df, df2, left_on='id', right_on='employee_id')

In [ ]:
company_df

,id,department_x,location,role,resign,employee_id,department_y,career,teamwork,reward,environment
0,101929,HR,China,Staff,Y,101929,HR,2,3,2,3
1,101625,Finance,US,Senior Director,N,101625,Finance,2,2,3,1
2,101318,IT,Japan,Senior Staff,N,101318,IT,2,3,5,5
3,100936,HR,Japan,Manager,Y,100936,HR,3,2,2,4
4,100125,HR,Korea,Senior Staff,N,100125,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...
71,102031,IT,Colombia,Senior Manager,Y,102031,IT,1,3,3,1
72,100476,HR,Colombia,Senior Manager,Y,100476,HR,1,2,3,5
73,100226,HR,UK,Senior Manager,N,100226,HR,2,2,3,4
74,101331,IT,Korea,Manager,N,101331,IT,3,5,4,4
75,100233,Sales,Japan,Staff,N,100233,Sales,4,2,2,5

#실습 설명
##소행성 정보를 담고 있는 asteroid_df와 각 소행성이 속한 궤도 관련 정보를 담고 있는 orbit_df를 하나로 합쳐서, 각 소행성이 지구와 충돌할 위험이 있는지 확인하려고 합니다. 두 데이터를 inner join한 결과물을 nasa_df라는 변수에 저장해 주세요.

##참고로 asteroid_df와 orbit_df는 NASA에서 제공한 데이터를 가공해서 만든 데이터로, 조금 어렵고 복잡해 보일 수도 있는데요. 일단 지금은 각 컬럼의 의미보다는 조인 연산 과정에 좀 더 집중해서 데이터를 탐색해 주시면 됩니다.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/asteroid.csv')

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/코드잇csv/orbit.csv')

In [ ]:
df

,id,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity
0,3753583,24.922,0.027552,0.061608,78734.416695
1,3736681,21.200,0.152952,0.342011,78315.420560
2,2226514,20.100,0.253837,0.567597,103175.288522
3,3674619,21.300,0.146068,0.326618,70196.294986
4,3608670,25.100,0.025384,0.056760,26652.631636
...,...,...,...,...,...
337,2468727,20.800,0.183889,0.411188,40225.448389
338,3736502,21.400,0.139494,0.311918,60813.804409
339,3738553,25.000,0.026580,0.059435,26988.425817
340,3484640,20.200,0.242412,0.542051,48648.982689
341,2041429,20.600,0.201630,0.450858,51264.256945

In [ ]:
df2

     asteroid_id  orbit_id  min_orbit_inter  perihelion_dist  inclination
0        2489486        45         0.020437         0.924281    15.090005
1        2196068        38         0.026944         0.710371    59.379202
2        2177049        79         0.000143         0.546414     0.650215
3        2465617        22         0.032103         0.956639     9.111115
4        3758926         9         0.035563         0.853339    30.576089
..           ...       ...              ...              ...          ...
145      2418849        39         0.035770         0.897503    33.524100
146      2141851        96         0.037918         0.179558    19.175872
147      2162882        81         0.032884         0.463728     6.497318
148      2382406        28         0.004718         0.286323     2.536137
149      3182172        36         0.032270         0.656464    32.829100

[150 rows x 5 columns]

In [ ]:
nasa_df = pd.merge(df, df2, left_on='id', right_on='asteroid_id')

In [ ]:
nasa_df

,id,abs_magnitude,min_est_diameter,max_est_diameter,relative_velocity,asteroid_id,orbit_id,min_orbit_inter,perihelion_dist,inclination
0,2226514,20.1,0.253837,0.567597,103175.288522,2226514,54,0.015130,0.420701,2.564450
1,3674619,21.3,0.146068,0.326618,70196.294986,3674619,8,0.018203,0.355309,2.544707
2,3644702,20.2,0.242412,0.542051,111504.879722,3644702,43,0.039390,0.468663,29.290232
3,3019647,20.6,0.201630,0.450858,86093.161070,3019647,16,0.024227,0.318180,19.803694
4,2208115,20.7,0.192555,0.430566,45195.716041,2208115,29,0.013353,0.838391,23.293402
...,...,...,...,...,...,...,...,...,...,...
152,2085938,18.6,0.506471,1.132505,48435.858841,2085938,112,0.022124,0.956925,9.145916
153,3745504,21.7,0.121494,0.271669,113607.187316,3745504,23,0.023437,0.639498,5.151032
154,2468727,20.8,0.183889,0.411188,40225.448389,2468727,29,0.034385,0.509222,16.920882
155,3736502,21.4,0.139494,0.311918,60813.804409,3736502,17,0.021474,0.948154,8.061251
156,2041429,20.6,0.201630,0.450858,51264.256945,2041429,68,0.010898,0.708209,2.173195

#인덱스 기준으로 데이터 합치기: join()

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/employee.csv')

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/코드잇csv/survey.csv')

In [ ]:
df

        id department  location             role resign
0   101929         HR     China            Staff      Y
1   101625    Finance        US  Senior Director      N
2   100298         HR     China          Manager      N
3   101870    Finance  Colombia          Manager      N
4   101318         IT     Japan     Senior Staff      N
..     ...        ...       ...              ...    ...
95  100476         HR  Colombia   Senior Manager      Y
96  100226         HR        UK   Senior Manager      N
97  101331         IT     Korea          Manager      N
98  100036         HR        UK          Manager      N
99  100233      Sales     Japan            Staff      N

[100 rows x 5 columns]

In [ ]:
df2

        id department  career  teamwork  reward  environment
0   101355         HR       5         4       5            4
1   100077      Sales       2         2       4            3
2   101844    Finance       2         3       1            5
3   101929         HR       2         3       2            3
4   101888         HR       4         4       3            3
..     ...        ...     ...       ...     ...          ...
71  101449         HR       4         3       3            5
72  101423    Finance       1         2       1            4
73  101098         IT       1         3       4            4
74  100618         IT       5         2       1            2
75  100488    Finance       5         4       1            5

[76 rows x 6 columns]

In [ ]:
#각각의 사원아이디를 인덱스로 설정하자
df = df.set_index('id')
df2 = df2.set_index('id')

In [ ]:
#merge()는 컬럼에 겹치는 이름들이 있으면 자동으로 뒤에 _x,_y를 해주지만
#join()는 따로 suffix 값을 설정해야 한다

In [ ]:
#df는 왼쪽데이터에, df2는 오른쪽에 합쳐지게 됨
df.join(df2, lsuffix='_x', rsuffix='_y')

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2.0,3.0,2.0,3.0
101625,Finance,US,Senior Director,N,Finance,2.0,2.0,3.0,1.0
100298,HR,China,Manager,N,NaN,NaN,NaN,NaN,NaN
101870,Finance,Colombia,Manager,N,NaN,NaN,NaN,NaN,NaN
101318,IT,Japan,Senior Staff,N,IT,2.0,3.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...
100476,HR,Colombia,Senior Manager,Y,HR,1.0,2.0,3.0,5.0
100226,HR,UK,Senior Manager,N,HR,2.0,2.0,3.0,4.0
101331,IT,Korea,Manager,N,IT,3.0,5.0,4.0,4.0
100036,HR,UK,Manager,N,NaN,NaN,NaN,NaN,NaN
100233,Sales,Japan,Staff,N,Sales,4.0,2.0,2.0,5.0

In [ ]:
#인어조인을 통해 설문조사를 진행한 데이터들만 불러오자
df.join(df2, lsuffix='_x', rsuffix='_y',how='inner')

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2,3,2,3
101625,Finance,US,Senior Director,N,Finance,2,2,3,1
101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
100936,HR,Japan,Manager,Y,HR,3,2,2,4
100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...
102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
100226,HR,UK,Senior Manager,N,HR,2,2,3,4
101331,IT,Korea,Manager,N,IT,3,5,4,4
100233,Sales,Japan,Staff,N,Sales,4,2,2,5

In [ ]:
#위 데이터를 df에 저장하면 2개의 데이터를 함친 데이터가 나타남
df= df.join(df2, lsuffix='_x', rsuffix='_y',how='inner')

In [ ]:
df

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2,3,2,3
101625,Finance,US,Senior Director,N,Finance,2,2,3,1
101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
100936,HR,Japan,Manager,Y,HR,3,2,2,4
100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...
102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
100226,HR,UK,Senior Manager,N,HR,2,2,3,4
101331,IT,Korea,Manager,N,IT,3,5,4,4
100233,Sales,Japan,Staff,N,Sales,4,2,2,5

# 조인한 데이터로 새로운 인사이트 얻기

In [ ]:
df

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2,3,2,3
101625,Finance,US,Senior Director,N,Finance,2,2,3,1
101318,IT,Japan,Senior Staff,N,IT,2,3,5,5
100936,HR,Japan,Manager,Y,HR,3,2,2,4
100125,HR,Korea,Senior Staff,N,HR,3,4,4,4
...,...,...,...,...,...,...,...,...,...
102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5
100226,HR,UK,Senior Manager,N,HR,2,2,3,4
101331,IT,Korea,Manager,N,IT,3,5,4,4
100233,Sales,Japan,Staff,N,Sales,4,2,2,5

In [ ]:
#퇴사하는 직원들이 많으니 그 원인을 분석해보자! 퇴사한 인원들만 불러오자
condition = df['resign'] == 'Y'

In [ ]:
df[condition]

,department_x,location,role,resign,department_y,career,teamwork,reward,environment
id,,,,,,,,,
101929,HR,China,Staff,Y,HR,2,3,2,3
100936,HR,Japan,Manager,Y,HR,3,2,2,4
101423,Finance,US,Manager,Y,Finance,1,2,1,4
100077,Sales,Australia,Staff,Y,Sales,2,2,4,3
100238,IT,US,Staff,Y,IT,2,1,1,5
101639,Sales,China,Senior Staff,Y,Sales,3,3,5,5
101718,Sales,Colombia,Manager,Y,Sales,4,1,4,4
101098,IT,France,Senior Staff,Y,IT,1,3,4,4
100595,HR,Colombia,Senior Manager,Y,HR,2,2,3,1
101849,HR,Colombia,Senior Staff,Y,HR,3,2,1,2
101758,Sales,Korea,Staff,Y,Sales,2,3,4,1
101125,Sales,Turkey,Manager,Y,Sales,3,5,3,3
100783,Sales,UK,Director,Y,Sales,3,1,5,5
101780,HR,Turkey,Senior Director,Y,HR,2,5,4,1
100644,Sales,Australia,Manager,Y,Sales,1,4,3,2
100488,Finance,Japan,Senior Staff,Y,Finance,5,4,1,5
100199,IT,France,Senior Staff,Y,IT,1,4,5,3
102031,IT,Colombia,Senior Manager,Y,IT,1,3,3,1
100476,HR,Colombia,Senior Manager,Y,HR,1,2,3,5

In [ ]:
#퇴사자들의 통계값
df[condition].describe()

          career   teamwork     reward  environment
count  19.000000  19.000000  19.000000    19.000000
mean    2.210526   2.736842   3.052632     3.210526
std     1.134262   1.240166   1.393385     1.512134
min     1.000000   1.000000   1.000000     1.000000
25%     1.000000   2.000000   2.000000     2.000000
50%     2.000000   3.000000   3.000000     3.000000
75%     3.000000   3.500000   4.000000     4.500000
max     5.000000   5.000000   5.000000     5.000000

In [ ]:
#이번에는 퇴사하지 않은 직원들의 정보를 불러오자
condition2 = df['resign'] == 'N'

In [ ]:
df[condition2].describe()

          career   teamwork     reward  environment
count  57.000000  57.000000  57.000000    57.000000
mean    3.228070   2.964912   3.140351     3.315789
std     1.267978   1.335837   1.444677     1.489941
min     1.000000   1.000000   1.000000     1.000000
25%     2.000000   2.000000   2.000000     2.000000
50%     3.000000   3.000000   3.000000     3.000000
75%     4.000000   4.000000   5.000000     5.000000
max     5.000000   5.000000   5.000000     5.000000

In [ ]:
#평균값에서 큰 차이가 보인다
#퇴사자들읜 상대적으로 커리어개발에 대한 만족도가 떨어졌다는 것을 알 수 있음
#해서 인사팀에서는 커리어개발을 위한 프로그램 할 수 있는 해결책을 낼 수 있음

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/코드잇csv/olympic.csv')